using Newtonsoft.Json;

namespace OWTChallenge.API.Models
{
    public class CompleteSkillDTO : CreateSkillDTO
    {
        // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
        public CompleteSkillDTO(int id, string name, List<ContactLevelDTO>? contactlevels = null) : base(name)
        {
            Id = id;
            ContactLevels = contactlevels ?? new List<ContactLevelDTO>();
        }

        #region Properties
        public int Id { get; set; }
        public List<ContactLevelDTO> ContactLevels { get; set; }
        #endregion


    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public abstract class CreateSkillDTO 
    {
        protected CreateSkillDTO(string name)
        {
            Name = name;
        }
        public string Name { get; set; } = null!;

    }
}
